#!/usr/bin/env python3
"""Create a portable Markdown + JSON + assets Typst project from bundled templates."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "templates" / "project"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--title", default="Application Report")
    parser.add_argument("--author", default="Application")
    parser.add_argument("--force", action="store_true", help="Replace only files generated by this bootstrapper")
    return parser.parse_args()


def generated_paths() -> tuple[str, ...]:
    return (
        "assets",
        "schema",
        "config.json",
        "content.md",
        "data.json",
        "main.typ",
        "theme.typ",
        "project-manifest.json",
    )


def refuse_conflicts(output: Path, force: bool) -> None:
    conflicts = [output / relative for relative in generated_paths() if (output / relative).exists()]
    if conflicts and not force:
        joined = ", ".join(str(path) for path in conflicts)
        raise SystemExit(f"Refusing to overwrite existing project paths: {joined}. Use --force to replace them.")


def copy_template(output: Path) -> None:
    for item in TEMPLATE.iterdir():
        destination = output / item.name
        if item.is_dir():
            shutil.copytree(item, destination, dirs_exist_ok=True)
        else:
            shutil.copy2(item, destination)


def write_manifest(output: Path, title: str, author: str) -> None:
    payload = {
        "schema_version": 1,
        "generator": "portable-typst-pdf-generator",
        "entry": "main.typ",
        "content": "content.md",
        "data": "data.json",
        "config": "config.json",
        "theme": "theme.typ",
        "title": title,
        "author": author,
    }
    (output / "project-manifest.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def main() -> int:
    args = parse_args()
    if not TEMPLATE.is_dir():
        raise SystemExit(f"Missing project template directory: {TEMPLATE}")

    output = args.output_dir.expanduser().resolve()
    output.mkdir(parents=True, exist_ok=True)
    refuse_conflicts(output, args.force)
    copy_template(output)

    config_path = output / "config.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))
    config["document"]["title"] = args.title
    config["document"]["author"] = args.author
    config_path.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    write_manifest(output, args.title, args.author)
    print(f"PROJECT READY root={output} entry={output / 'main.typ'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
